--- 
title: "Meeting Patterns"
author: ["Toli Apostolidis","Ian K Salter"]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This book describes a number of different patters for running meetings"
---

# Introducton

Purpose of book:

* Enable meeting organisers to choose the appropriate form for their meeting.
* Enable meeting participitants to understand ground rules for a given meeting type.

The book result of participation a Democracy in Europe Movement (DiEM) movement meeting held in February 2019. Movitations for creating this work are further discussed in Appendix 1 and 2.

TODO: Stuff about why and what and how patterns are structured. Every pattern has a description and pros and cons. The additional components of meeting pattern structure are described below.

## Meeting Purpose

A non exclusive list:

* Understanding
* Topic Selection
* Goal Setting
* Solution Finding
* Information Provision
* Reporting Progress
* Providing Feedback

## Number of Participants

A non exclusive list:

* One to One
* Very Small Group < 5
* Small Group < 20
* Large Group > 20


## Meeting Medium

A non exclusive list:

* Face to Face
* Video Conferance
* Audio Conferennce

## Participent Type

A non exclusive list:

* Server - Client (need a different term)
    + Lecturer
    + Audience Member
    + Chair
    + Speaker
* Peer to peer (may need a different term)
    + Participant
    + Facilitator
    + Summariser


## Participation Style

 (may split by participant types???):

* Telling - "This is this, that is that ...."
* Sharing - "I feel that, its seems to me that, I see this in a diffent way"
* Clarity Querstioning - "I didn't understand that point""
* Approach Questioning - "I think this should be done a different way"
* Managing * Shared note taking
* Sumarising



## Materials

A non exclusive list

* Presentation Slides
* Flip Charts
* White Boards
* Documents
* Pens
* Paper
* Post It Notes
* Task Board JIRA









